### ISSUE TITLE
Time difference error does is not clear when the time difference is less than 1s

### ISSUE THREAD

**Issue by kayhadrin** [gaslight/chai-datetime#18]
Example of comparing two dates that differ by less than 1 second: `expect(actualUTCDate).to.equalTime yesterdayStartOfDayUTC`

Output (indented for clarity): 

```
AssertionError: expected 
Mon Mar 23 2015 11:00:00 GMT+1100 (AUS Eastern Daylight Time) to equal 
Mon Mar 23 2015 11:00:00 GMT+1100 (AUS Eastern Daylight Time)
```

It would be nice if the time difference found between two different dates could be given to avoid confusion.

**Comment by mguterl** [comment]
@kayhadrin thanks for the feedback. I'll look into some ways to include and format this information.

**Comment by kayhadrin** [comment]
Cheers.

I've also tried to use this plugin with chai-as-promised but it seems not to work properly yet.
Have you tried using it with it before?

**Comment by mguterl** [comment]
@kayhadrin I have never used chai-as-promised before. Would you mind filing a separate issue with some more information so I can look into it?

**Comment by mguterl** [comment]
@kayhadrin does @ktornwall's PR #22 help with your issue? I know you asked to see the difference between the times, but I think @ktornwall's solution is simpler and solves the problem.

**Comment by kayhadrin** [comment]
That'd be just fine for me indeed :-)
